name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create Temporary Branch
        run: |
          git checkout -b release-${{ github.event.inputs.version }}

      - name: Commit dist folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Update dist folder for release ${{ github.event.inputs.version }}"

      - name: Push Temporary Branch
        run: |
          git push origin release-${{ github.event.inputs.version }}

      - name: Create Release Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Changes in this release:
            - ...
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Temporary Branch
        run: |
          git push origin --delete release-${{ github.event.inputs.version }}