name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo "::set-output name=version::$(cat .nvmrc)"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.version }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create Temporary Branch
        run: |
          git checkout -b release

      - name: Temporarily unignore dist directory
        run: |
          sed -i '/dist/d' .gitignore

      - name: Commit and push dist folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Update dist folder"
          git push origin release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Changes in this release:
            - ...

      - name: Delete Temporary Branch
        run: |
          git push origin --delete release
