name: Manual Release test

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo "::set-output name=version::$(cat .nvmrc)"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.version }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create zip file
        run: |
          zip -r dist.zip dist

      - name: Release & Assets
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          asset_files: './dist.zip'
